### ISSUE TITLE
Coordinate with Dataverse upstream to incorporate optimizations

### ISSUE THREAD

**Issue by poikilotherm** [gdcc/xoai#10]
The Dataverse main software uses this library to create an OAI-PMH server. To achieve maximum performance, they kind of forked some of the classes this library provides, copying most of the code.

As this is now a fork under the control of GDCC, it would make sense to change the library classes to provide useful extension points that Dataverse codebase could use then to avoid maintaining forked classes.

@landreev WDYT?

The respective Dataverse classes can be found here: 
- [edu.harvard.iq.dataverse.harvest.server.xoai](https://github.com/IQSS/dataverse/tree/develop/src/main/java/edu/harvard/iq/dataverse/harvest/server/xoai)

**Comment by pdurbin** [comment]
Related:

- https://github.com/IQSS/dataverse/issues/8372
