### ISSUE TITLE
Release 5.0.0 final version

### ISSUE THREAD

**Issue by poikilotherm** [gdcc/xoai#59]

**Comment by poikilotherm** [comment]
I think with there merge of #118, #122 and #123 we got much nearer to maturity of this library after the fork and refactoring.

Maybe it's time to cut a first release of the 5.x branch, not just RCs.

**Comment by landreev** [comment]
I'm all in support of cutting a "real" 5.0.0. 
(sorry if I'm posting this comment the second time around - ?)

**Comment by landreev** [comment]
I just asked a question on slack, about one other aspect of handling of date parameters. It's not super important, and I may be completely wrong there. But it would be great to actually confirm what the answer is, before 5.0.0 is released.

**Comment by landreev** [comment]
I have a complaint: why is this issue still open?

**Comment by poikilotherm** [comment]
5.0 was just released and is now available via Maven Central. https://repo1.maven.org/maven2/io/gdcc/xoai/5.0.0/

Closing this as done!
